# Generated by Django 3.1.7 on 2021-04-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210405_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('cart', 'Cart'), ('order', 'Order'), ('send', 'Send')], default='cart', max_length=10),
        ),
    ]
